const { withEntitlementsPlist } = require('@expo/config-plugins');

/**
 * Expo config plugin that enables APNs (Apple Push Notifications) on iOS.
 *
 * FCM cannot mint a token on iOS without an APNs token, and iOS will not issue
 * an APNs token without the aps-environment entitlement. Without this,
 * messaging().getToken() rejects with "No APNS token specified" and the band
 * can never be reached by a pushed alert.
 *
 * ios/ is regenerated by prebuild and gitignored, so the entitlement has to be
 * injected here rather than edited into the Xcode project by hand.
 *
 * The value must match the provisioning profile: 'development' for dev/preview
 * builds, 'production' for TestFlight and the App Store. EAS rewrites this at
 * build time to match the profile it signs with, but setting it explicitly
 * keeps local `expo run:ios` builds working.
 */
function withPushNotifications(config) {
  return withEntitlementsPlist(config, (config) => {
    config.modResults['aps-environment'] =
      process.env.APS_ENVIRONMENT ?? 'development';
    return config;
  });
}

module.exports = withPushNotifications;
